import {
  Zap,
  FlaskConical,
  FileText,
  ShieldCheck,
  Clock,
  Gauge,
} from "lucide-react";

export const IPC_ANNOUNCEMENTS = [
  {
    id: "ann-1",
    category: "IP 2026 Monograph",
    categoryHi: "भेषज संहिता 2026",
    title: "Indian Pharmacopoeia (IP 2026) Addendum Draft Release",
    titleHi: "भारतीय भेषज संहिता (IP 2026) परिशिष्ट प्रारूप जारी",
    summary:
      "Draft addendum containing 48 new API & formulation monographs is open for stakeholder feedback.",
    date: "2026-08-25",
    priority: "high",
    icon: FileText,
    badgeColor: "bg-amber-500/15 text-amber-700 border-amber-300/50",
    dotColor: "bg-amber-500",
    refCode: "IPC/IP-ADD/2026/04",
  },
  {
    id: "ann-2",
    category: "24H SLA Policy",
    categoryHi: "24H एसएलए नीति",
    title:
      "Strict 24-Hour SLA Mandatory for High Priority (P1) Technical Queries",
    titleHi: "उच्च प्राथमिकता (P1) प्रश्नों हेतु 24 घंटे की एसएलए अनिवार्य",
    summary:
      "All P1 queries submitted via BRIDGETECH must be acknowledged, assigned, and verified within 24 hours.",
    date: "2026-08-26",
    priority: "high",
    icon: Zap,
    badgeColor: "bg-rose-500/15 text-rose-700 border-rose-300/50",
    dotColor: "bg-rose-500",
    refCode: "SOP-IPC-BRIDGETECH-V4.2",
  },
  {
    id: "ann-3",
    category: "Reference Standards",
    categoryHi: "संदर्भ मानक",
    title: "Updated Reference Standards & Impurities Catalog Released",
    titleHi: "अद्यतन संदर्भ मानक और अशुद्धता सूची जारी",
    summary:
      "National Pharmacopoeia Laboratory (NPL) has published new reference standard batches for active drug ingredients.",
    date: "2026-08-24",
    priority: "medium",
    icon: FlaskConical,
    badgeColor: "bg-blue-500/15 text-blue-700 border-blue-300/50",
    dotColor: "bg-blue-500",
    refCode: "IPC/QC-STD/2026/89",
  },
  {
    id: "ann-4",
    category: "MoHFW Directive",
    categoryHi: "स्वास्थ्य मंत्रालय निर्देश",
    title: "Mandatory Digital Query Submission via BRIDGETECH Portal",
    titleHi: "BRIDGETECH पोर्टल के माध्यम से डिजिटल प्रश्न पंजीकरण अनिवार्य",
    summary:
      "Ministry of Health & Family Welfare directs all drug manufacturers to submit official technical queries online.",
    date: "2026-08-22",
    priority: "high",
    icon: ShieldCheck,
    badgeColor: "bg-purple-500/15 text-purple-700 border-purple-300/50",
    dotColor: "bg-purple-500",
    refCode: "MOHFW-DIR-2026/IPC-01",
  },
  {
    id: "ann-5",
    category: "KPI Benchmark",
    categoryHi: "केपीआई बेंचमार्क",
    title: "Quarterly Target Resolution Time: ≤ 2.5 Business Days",
    titleHi: "त्रैमासिक औसत समाधान समय लक्ष्य: ≤ 2.5 कार्य दिवस",
    summary:
      "Division heads and reviewers are urged to process pending reviews promptly to maintain 98%+ SLA compliance.",
    date: "2026-08-20",
    priority: "medium",
    icon: Gauge,
    badgeColor: "bg-emerald-500/15 text-emerald-700 border-emerald-300/50",
    dotColor: "bg-emerald-500",
    refCode: "IPC-KPI-Q3-2026",
  },
  {
    id: "ann-6",
    category: "ISO Audit",
    categoryHi: "आईएसओ लेखा परीक्षा",
    title: "ISO/IEC 17025:2017 Internal Laboratory Audit Scheduled",
    titleHi: "ISO/IEC 17025:2017 आंतरिक गुणवत्ता लेखा परीक्षा",
    summary:
      "Annual quality assurance audit for IPC laboratories scheduled from 15th to 20th September 2026.",
    date: "2026-08-18",
    priority: "info",
    icon: Clock,
    badgeColor: "bg-cyan-500/15 text-cyan-700 border-cyan-300/50",
    dotColor: "bg-cyan-500",
    refCode: "AUD-ISO-17025-2026",
  },
];
