/**
 * Business Status vs Workflow State (see docs/srs/05-workflow-and-state-machine.md):
 *
 * - BUSINESS_STATUS is the coarse, client-facing lifecycle summary (is the
 *   query open, being worked, or closed). It's what an inquirer would see.
 * - WORKFLOW_STATE is the fine-grained internal step the query instance is
 *   currently sitting at. Many WORKFLOW_STATE values map to a single
 *   BUSINESS_STATUS (e.g. ASSIGNED, DRAFTING, and UNDER_REVIEW are all
 *   BUSINESS_STATUS "IN_PROGRESS").
 *
 * The two are tracked as separate fields on a Query — never derive one by
 * parsing the other's string value.
 */

export const BUSINESS_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED',
};

export const WORKFLOW_STATE = {
  RECEIVED: 'RECEIVED',
  FRONT_OFFICE_VERIFICATION: 'FRONT_OFFICE_VERIFICATION',
  PENDING_ASSIGNMENT: 'PENDING_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  DRAFTING: 'DRAFTING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PENDING_FINAL_APPROVAL: 'PENDING_FINAL_APPROVAL',
  APPROVED: 'APPROVED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  CLOSED: 'CLOSED',
  RETURNED_FOR_REVISION: 'RETURNED_FOR_REVISION',
  TRANSFERRED: 'TRANSFERRED',
  PULLED_BACK: 'PULLED_BACK',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED',
};

export const PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const AUDIT_EVENT = {
  QUERY_RECEIVED: 'QUERY_RECEIVED',
  QUERY_REGISTERED: 'QUERY_REGISTERED',
  QUERY_FORWARDED: 'QUERY_FORWARDED',
  QUERY_ASSIGNED: 'QUERY_ASSIGNED',
  ASSIGNMENT_OVERRIDDEN: 'ASSIGNMENT_OVERRIDDEN',
  DRAFT_GENERATED: 'DRAFT_GENERATED',
  DRAFT_UPDATED: 'DRAFT_UPDATED',
  REVIEW_ADDED: 'REVIEW_ADDED',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  QUERY_TRANSFERRED: 'QUERY_TRANSFERRED',
  QUERY_PULLED_BACK: 'QUERY_PULLED_BACK',
  FINAL_APPROVAL_GRANTED: 'FINAL_APPROVAL_GRANTED',
  FINAL_APPROVAL_REJECTED: 'FINAL_APPROVAL_REJECTED',
  RESPONSE_DISPATCHED: 'RESPONSE_DISPATCHED',
  QUERY_CLOSED: 'QUERY_CLOSED',
};
