export const BUSINESS_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED',
};

export const WORKFLOW_STATE = {
  RECEIVED: 'RECEIVED',
  FRONT_OFFICE_VERIFICATION: 'FRONT_OFFICE_VERIFICATION',
  PENDING_ASSIGNMENT: 'PENDING_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  DRAFTING: 'DRAFTING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PENDING_FINAL_APPROVAL: 'PENDING_FINAL_APPROVAL',
  APPROVED: 'APPROVED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  CLOSED: 'CLOSED',
  RETURNED_FOR_REVISION: 'RETURNED_FOR_REVISION',
  TRANSFERRED: 'TRANSFERRED',
  PULLED_BACK: 'PULLED_BACK',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED',
};

export const RESPONSE_SOURCE = {
  AI_GENERATED: 'AI_GENERATED',
  USER_EDITED: 'USER_EDITED',
  REVIEW_REVISION: 'REVIEW_REVISION',
};

export const RESPONSE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  FINAL_APPROVED: 'FINAL_APPROVED',
};

export const PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const AUDIT_EVENT = {
  QUERY_RECEIVED: 'QUERY_RECEIVED',
  ACKNOWLEDGEMENT_SENT: 'ACKNOWLEDGEMENT_SENT',
  AI_SUMMARY_GENERATED: 'AI_SUMMARY_GENERATED',
  AI_ASSIGNMENT_RECOMMENDED: 'AI_ASSIGNMENT_RECOMMENDED',
  QUERY_REGISTERED: 'QUERY_REGISTERED',
  QUERY_FORWARDED: 'QUERY_FORWARDED',
  QUERY_ASSIGNED: 'QUERY_ASSIGNED',
  ASSIGNMENT_OVERRIDDEN: 'ASSIGNMENT_OVERRIDDEN',
  DRAFT_GENERATED: 'DRAFT_GENERATED',
  DRAFT_UPDATED: 'DRAFT_UPDATED',
  REVIEW_ADDED: 'REVIEW_ADDED',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  QUERY_TRANSFERRED: 'QUERY_TRANSFERRED',
  QUERY_PULLED_BACK: 'QUERY_PULLED_BACK',
  FINAL_APPROVAL_GRANTED: 'FINAL_APPROVAL_GRANTED',
  FINAL_APPROVAL_REJECTED: 'FINAL_APPROVAL_REJECTED',
  RESPONSE_DISPATCHED: 'RESPONSE_DISPATCHED',
  QUERY_CLOSED: 'QUERY_CLOSED',
};
