import { BUSINESS_STATUS, WORKFLOW_STATE } from './statusEnums';
import { ROLES } from './roles';

export const WORKFLOW_ACTION = {
  VERIFY: 'VERIFY',
  FORWARD: 'FORWARD',
  ASSIGN: 'ASSIGN',
  GENERATE_AI_DRAFT: 'GENERATE_AI_DRAFT',
  SAVE_DRAFT: 'SAVE_DRAFT',
  SUBMIT_FOR_REVIEW: 'SUBMIT_FOR_REVIEW',
  APPROVE_REVIEW: 'APPROVE_REVIEW',
  REQUEST_REVISION: 'REQUEST_REVISION',
  ADD_REVIEW_LEVEL: 'ADD_REVIEW_LEVEL',
  DELETE_REVIEW_LEVEL: 'DELETE_REVIEW_LEVEL',
  FINAL_APPROVE: 'FINAL_APPROVE',
  FINAL_REJECT: 'FINAL_REJECT',
  RETURN_FOR_REVISION: 'RETURN_FOR_REVISION',
  DISPATCH: 'DISPATCH',
  TRANSFER: 'TRANSFER',
  PULLBACK: 'PULLBACK',
};

export const CLARIFICATION_REQUIRED_ACTIONS = {
  [WORKFLOW_ACTION.DELETE_REVIEW_LEVEL]: {
    label: 'Delete review level',
    openQuestions: ['Who can delete a review level, and under what conditions?'],
  },
};

export const ASSIGNEE_ONLY_ACTIONS = [
  WORKFLOW_ACTION.GENERATE_AI_DRAFT,
  WORKFLOW_ACTION.SAVE_DRAFT,
  WORKFLOW_ACTION.SUBMIT_FOR_REVIEW,
  WORKFLOW_ACTION.ADD_REVIEW_LEVEL,
  WORKFLOW_ACTION.TRANSFER,
];

export function isCaseAssignee(user, query) {
  if (user?.role === ROLES.SUPER_ADMIN) return true;
  return Boolean(query?.currentAssigneeId) && query.currentAssigneeId === user?.id;
}

export function deriveBusinessStatus(workflowState) {
  if (workflowState === WORKFLOW_STATE.RECEIVED) return BUSINESS_STATUS.OPEN;
  if (workflowState === WORKFLOW_STATE.CLOSED || workflowState === WORKFLOW_STATE.CANCELLED) {
    return BUSINESS_STATUS.CLOSED;
  }
  return BUSINESS_STATUS.IN_PROGRESS;
}

const ALL_WORKFLOW_STATES = Object.values(WORKFLOW_STATE);

const ROLE_ACTIONS = {
  [ROLES.FRONT_OFFICE]: [WORKFLOW_ACTION.VERIFY, WORKFLOW_ACTION.FORWARD, WORKFLOW_ACTION.DISPATCH],
  [ROLES.OFFICER_IN_CHARGE]: [
    WORKFLOW_ACTION.ASSIGN,
    WORKFLOW_ACTION.FINAL_APPROVE,
    WORKFLOW_ACTION.FINAL_REJECT,
    WORKFLOW_ACTION.RETURN_FOR_REVISION,
  ],
  [ROLES.ASSIGNED_OFFICIAL]: [
    WORKFLOW_ACTION.GENERATE_AI_DRAFT,
    WORKFLOW_ACTION.SAVE_DRAFT,
    WORKFLOW_ACTION.SUBMIT_FOR_REVIEW,
    WORKFLOW_ACTION.ADD_REVIEW_LEVEL,
    WORKFLOW_ACTION.TRANSFER,
  ],
  [ROLES.REVIEWER]: [WORKFLOW_ACTION.APPROVE_REVIEW, WORKFLOW_ACTION.REQUEST_REVISION],
  [ROLES.ADMIN]: [WORKFLOW_ACTION.PULLBACK],
  [ROLES.SUPER_ADMIN]: [
    WORKFLOW_ACTION.VERIFY,
    WORKFLOW_ACTION.FORWARD,
    WORKFLOW_ACTION.ASSIGN,
    WORKFLOW_ACTION.GENERATE_AI_DRAFT,
    WORKFLOW_ACTION.SAVE_DRAFT,
    WORKFLOW_ACTION.SUBMIT_FOR_REVIEW,
    WORKFLOW_ACTION.APPROVE_REVIEW,
    WORKFLOW_ACTION.REQUEST_REVISION,
    WORKFLOW_ACTION.ADD_REVIEW_LEVEL,
    WORKFLOW_ACTION.FINAL_APPROVE,
    WORKFLOW_ACTION.FINAL_REJECT,
    WORKFLOW_ACTION.RETURN_FOR_REVISION,
    WORKFLOW_ACTION.DISPATCH,
    WORKFLOW_ACTION.TRANSFER,
    WORKFLOW_ACTION.PULLBACK,
  ],
};

const ACTION_VALID_STATES = {
  [WORKFLOW_ACTION.VERIFY]: [WORKFLOW_STATE.RECEIVED],
  [WORKFLOW_ACTION.FORWARD]: [WORKFLOW_STATE.FRONT_OFFICE_VERIFICATION],
  [WORKFLOW_ACTION.ASSIGN]: [WORKFLOW_STATE.PENDING_ASSIGNMENT],
  [WORKFLOW_ACTION.GENERATE_AI_DRAFT]: [WORKFLOW_STATE.ASSIGNED, WORKFLOW_STATE.DRAFTING],
  [WORKFLOW_ACTION.SAVE_DRAFT]: [
    WORKFLOW_STATE.ASSIGNED,
    WORKFLOW_STATE.DRAFTING,
    WORKFLOW_STATE.RETURNED_FOR_REVISION,
  ],
  [WORKFLOW_ACTION.SUBMIT_FOR_REVIEW]: [WORKFLOW_STATE.DRAFTING, WORKFLOW_STATE.RETURNED_FOR_REVISION],
  [WORKFLOW_ACTION.APPROVE_REVIEW]: [WORKFLOW_STATE.UNDER_REVIEW],
  [WORKFLOW_ACTION.REQUEST_REVISION]: [WORKFLOW_STATE.UNDER_REVIEW],
  [WORKFLOW_ACTION.ADD_REVIEW_LEVEL]: [
    WORKFLOW_STATE.DRAFTING,
    WORKFLOW_STATE.UNDER_REVIEW,
    WORKFLOW_STATE.RETURNED_FOR_REVISION,
  ],
  [WORKFLOW_ACTION.FINAL_APPROVE]: [WORKFLOW_STATE.PENDING_FINAL_APPROVAL],
  [WORKFLOW_ACTION.FINAL_REJECT]: [WORKFLOW_STATE.PENDING_FINAL_APPROVAL],
  [WORKFLOW_ACTION.RETURN_FOR_REVISION]: [WORKFLOW_STATE.PENDING_FINAL_APPROVAL],
  [WORKFLOW_ACTION.DISPATCH]: [WORKFLOW_STATE.READY_FOR_DISPATCH],
  [WORKFLOW_ACTION.TRANSFER]: [WORKFLOW_STATE.ASSIGNED],
  [WORKFLOW_ACTION.PULLBACK]: ALL_WORKFLOW_STATES,
};

export function canPerform(role, action, workflowState) {
  if (CLARIFICATION_REQUIRED_ACTIONS[action]) return false;
  const allowedActions = ROLE_ACTIONS[role] || [];
  if (!allowedActions.includes(action)) return false;
  const validStates = ACTION_VALID_STATES[action] || [];
  return validStates.includes(workflowState);
}
