export const AUDIT_ACTIONS = {
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',

  EMAIL_RECEIVED: 'EMAIL_RECEIVED',
  EMAIL_READ: 'EMAIL_READ',
  EMAIL_CLASSIFIED: 'EMAIL_CLASSIFIED',
  ATTACHMENT_UPLOADED: 'ATTACHMENT_UPLOADED',
  ATTACHMENT_DOWNLOADED: 'ATTACHMENT_DOWNLOADED',

  CASE_CREATED: 'CASE_CREATED',
  CASE_ASSOCIATED: 'CASE_ASSOCIATED',
  CASE_ASSOCIATION_CHANGED: 'CASE_ASSOCIATION_CHANGED',

  AI_SUMMARY_GENERATED: 'AI_SUMMARY_GENERATED',
  AI_DRAFT_GENERATED: 'AI_DRAFT_GENERATED',
  AI_RECOMMENDATION_GENERATED: 'AI_RECOMMENDATION_GENERATED',

  DRAFT_CREATED: 'DRAFT_CREATED',
  DRAFT_EDITED: 'DRAFT_EDITED',
  DRAFT_SUBMITTED_FOR_APPROVAL: 'DRAFT_SUBMITTED_FOR_APPROVAL',
  DRAFT_APPROVED: 'DRAFT_APPROVED',
  DRAFT_REJECTED: 'DRAFT_REJECTED',

  EMAIL_SENT: 'EMAIL_SENT',
  EMAIL_REPLIED: 'EMAIL_REPLIED',
  EMAIL_FORWARDED: 'EMAIL_FORWARDED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  SENT_APPEND_FAILED: 'SENT_APPEND_FAILED',
  EMAIL_DELIVERY_CONFIRMED: 'EMAIL_DELIVERY_CONFIRMED',
  EMAIL_DELIVERY_DENIED: 'EMAIL_DELIVERY_DENIED',

  EMAIL_MARKED_READ: 'EMAIL_MARKED_READ',
  EMAIL_MARKED_UNREAD: 'EMAIL_MARKED_UNREAD',
  EMAIL_MOVED: 'EMAIL_MOVED',
  EMAIL_DELETED: 'EMAIL_DELETED',
  EMAIL_PURGED: 'EMAIL_PURGED',

  SYNC_STARTED: 'SYNC_STARTED',
  SYNC_COMPLETED: 'SYNC_COMPLETED',
  SYNC_FAILED: 'SYNC_FAILED',
  SYNC_RECOVERED: 'SYNC_RECOVERED',
  UIDVALIDITY_CHANGED: 'UIDVALIDITY_CHANGED',
  CREDENTIAL_ROTATED: 'CREDENTIAL_ROTATED',
};

export const AUDIT_RESULTS = {
  SUCCESS: 'success',
  FAILURE: 'failure',
  DENIED: 'denied',
};

export const ALL_AUDIT_ACTIONS = Object.values(AUDIT_ACTIONS);

export const CLIENT_AUDIT_EVENTS = [
  'QUERY_RECEIVED',
  'ACKNOWLEDGEMENT_SENT',
  'AI_SUMMARY_GENERATED',
  'AI_ASSIGNMENT_RECOMMENDED',
  'QUERY_REGISTERED',
  'QUERY_FORWARDED',
  'QUERY_ASSIGNED',
  'ASSIGNMENT_OVERRIDDEN',
  'DRAFT_GENERATED',
  'DRAFT_UPDATED',
  'REVIEW_ADDED',
  'REVIEW_COMPLETED',
  'REVISION_REQUESTED',
  'QUERY_TRANSFERRED',
  'QUERY_PULLED_BACK',
  'FINAL_APPROVAL_GRANTED',
  'FINAL_APPROVAL_REJECTED',
  'RESPONSE_DISPATCHED',
  'QUERY_CLOSED',
];

const KNOWN_EVENTS = new Set([...ALL_AUDIT_ACTIONS, ...CLIENT_AUDIT_EVENTS]);

export const isKnownAuditAction = (action) => KNOWN_EVENTS.has(action);
