import { WORKFLOW_ACTION } from './workflowActions.js';
import { WORKFLOW_STATE, RESPONSE_STATUS } from './workflowStates.js';

const { VERIFY, FORWARD, ASSIGN, GENERATE_AI_DRAFT, SAVE_DRAFT, SUBMIT_FOR_REVIEW, APPROVE_REVIEW,
  REQUEST_REVISION, FINAL_APPROVE, RETURN_FOR_REVISION, DISPATCH, TRANSFER, PULLBACK } = WORKFLOW_ACTION;

export const STATE_REQUIRES_ACTION = {
  [WORKFLOW_STATE.RECEIVED]: null,
  [WORKFLOW_STATE.FRONT_OFFICE_VERIFICATION]: [VERIFY],
  [WORKFLOW_STATE.PENDING_ASSIGNMENT]: [FORWARD],
  [WORKFLOW_STATE.ASSIGNED]: [ASSIGN],
  [WORKFLOW_STATE.DRAFTING]: [SAVE_DRAFT, GENERATE_AI_DRAFT],
  [WORKFLOW_STATE.UNDER_REVIEW]: [SUBMIT_FOR_REVIEW, APPROVE_REVIEW],
  [WORKFLOW_STATE.PENDING_FINAL_APPROVAL]: [APPROVE_REVIEW, SUBMIT_FOR_REVIEW],
  [WORKFLOW_STATE.APPROVED]: [FINAL_APPROVE],
  [WORKFLOW_STATE.READY_FOR_DISPATCH]: [FINAL_APPROVE],
  [WORKFLOW_STATE.DISPATCHED]: [DISPATCH],
  [WORKFLOW_STATE.CLOSED]: [DISPATCH, FINAL_APPROVE],
  [WORKFLOW_STATE.RETURNED_FOR_REVISION]: [REQUEST_REVISION, RETURN_FOR_REVISION],
  [WORKFLOW_STATE.TRANSFERRED]: [TRANSFER],
  [WORKFLOW_STATE.PULLED_BACK]: [PULLBACK],
  [WORKFLOW_STATE.ON_HOLD]: null,
  [WORKFLOW_STATE.CANCELLED]: null,
};

export const VERSION_STATUS_REQUIRES_ACTION = {
  [RESPONSE_STATUS.DRAFT]: null,
  [RESPONSE_STATUS.SUBMITTED]: [SUBMIT_FOR_REVIEW, SAVE_DRAFT],
  [RESPONSE_STATUS.FINAL_APPROVED]: [FINAL_APPROVE],
};

export const ASSIGNEE_REQUIRES_ACTION = [ASSIGN, TRANSFER, PULLBACK];
