export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  FRONT_OFFICE: 'FRONT_OFFICE',
  OFFICER_IN_CHARGE: 'OFFICER_IN_CHARGE',
  ASSIGNED_OFFICIAL: 'ASSIGNED_OFFICIAL',
  REVIEWER: 'REVIEWER',
};

export const ACTOR_TYPES = {
  HUMAN: 'human',
  AGENT: 'agent',
  SYSTEM: 'system',
};
