export const BUSINESS_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED',
};

export const WORKFLOW_STATE = {
  RECEIVED: 'RECEIVED',
  FRONT_OFFICE_VERIFICATION: 'FRONT_OFFICE_VERIFICATION',
  PENDING_ASSIGNMENT: 'PENDING_ASSIGNMENT',
  ASSIGNED: 'ASSIGNED',
  DRAFTING: 'DRAFTING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PENDING_FINAL_APPROVAL: 'PENDING_FINAL_APPROVAL',
  APPROVED: 'APPROVED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  CLOSED: 'CLOSED',
  RETURNED_FOR_REVISION: 'RETURNED_FOR_REVISION',
  TRANSFERRED: 'TRANSFERRED',
  PULLED_BACK: 'PULLED_BACK',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED',
};

export const RESPONSE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  FINAL_APPROVED: 'FINAL_APPROVED',
};

export const PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const ALL_WORKFLOW_STATES = Object.values(WORKFLOW_STATE);
export const ALL_RESPONSE_STATUSES = Object.values(RESPONSE_STATUS);
export const ALL_BUSINESS_STATUSES = Object.values(BUSINESS_STATUS);
export const ALL_PRIORITIES = Object.values(PRIORITY);
export const NEEDS_APPROVAL = [WORKFLOW_STATE.PENDING_FINAL_APPROVAL, WORKFLOW_STATE.APPROVED];
export const ALREADY_APPROVED = [
  WORKFLOW_STATE.READY_FOR_DISPATCH,
  WORKFLOW_STATE.DISPATCHED,
  WORKFLOW_STATE.CLOSED,
];
