import { ROLES } from './roles.js';

export const WORKFLOW_ACTION = {
  VERIFY: 'VERIFY',
  FORWARD: 'FORWARD',
  ASSIGN: 'ASSIGN',
  GENERATE_AI_DRAFT: 'GENERATE_AI_DRAFT',
  SAVE_DRAFT: 'SAVE_DRAFT',
  SUBMIT_FOR_REVIEW: 'SUBMIT_FOR_REVIEW',
  APPROVE_REVIEW: 'APPROVE_REVIEW',
  REQUEST_REVISION: 'REQUEST_REVISION',
  ADD_REVIEW_LEVEL: 'ADD_REVIEW_LEVEL',
  DELETE_REVIEW_LEVEL: 'DELETE_REVIEW_LEVEL',
  FINAL_APPROVE: 'FINAL_APPROVE',
  FINAL_REJECT: 'FINAL_REJECT',
  RETURN_FOR_REVISION: 'RETURN_FOR_REVISION',
  DISPATCH: 'DISPATCH',
  TRANSFER: 'TRANSFER',
  PULLBACK: 'PULLBACK',
};

export const CLARIFICATION_REQUIRED_ACTIONS = [];

export const ROLE_ACTIONS = {
  [ROLES.FRONT_OFFICE]: [WORKFLOW_ACTION.VERIFY, WORKFLOW_ACTION.FORWARD, WORKFLOW_ACTION.DISPATCH],
  [ROLES.OFFICER_IN_CHARGE]: [
    WORKFLOW_ACTION.ASSIGN,
    WORKFLOW_ACTION.FINAL_APPROVE,
    WORKFLOW_ACTION.FINAL_REJECT,
    WORKFLOW_ACTION.RETURN_FOR_REVISION,
  ],
  [ROLES.ASSIGNED_OFFICIAL]: [
    WORKFLOW_ACTION.GENERATE_AI_DRAFT,
    WORKFLOW_ACTION.SAVE_DRAFT,
    WORKFLOW_ACTION.SUBMIT_FOR_REVIEW,
    WORKFLOW_ACTION.ADD_REVIEW_LEVEL,
    WORKFLOW_ACTION.DELETE_REVIEW_LEVEL,
    WORKFLOW_ACTION.TRANSFER,
  ],
  [ROLES.REVIEWER]: [WORKFLOW_ACTION.APPROVE_REVIEW, WORKFLOW_ACTION.REQUEST_REVISION],
  [ROLES.ADMIN]: [WORKFLOW_ACTION.PULLBACK],
  [ROLES.SUPER_ADMIN]: [
    WORKFLOW_ACTION.VERIFY,
    WORKFLOW_ACTION.FORWARD,
    WORKFLOW_ACTION.ASSIGN,
    WORKFLOW_ACTION.GENERATE_AI_DRAFT,
    WORKFLOW_ACTION.SAVE_DRAFT,
    WORKFLOW_ACTION.SUBMIT_FOR_REVIEW,
    WORKFLOW_ACTION.APPROVE_REVIEW,
    WORKFLOW_ACTION.REQUEST_REVISION,
    WORKFLOW_ACTION.ADD_REVIEW_LEVEL,
    WORKFLOW_ACTION.DELETE_REVIEW_LEVEL,
    WORKFLOW_ACTION.FINAL_APPROVE,
    WORKFLOW_ACTION.FINAL_REJECT,
    WORKFLOW_ACTION.RETURN_FOR_REVISION,
    WORKFLOW_ACTION.DISPATCH,
    WORKFLOW_ACTION.TRANSFER,
    WORKFLOW_ACTION.PULLBACK,
  ],
};

export function roleCanPerform(role, action) {
  if (CLARIFICATION_REQUIRED_ACTIONS.includes(action)) return false;
  return (ROLE_ACTIONS[role] || []).includes(action);
}
